version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      MSSQL_SA_PASSWORD: "r00tR00t"
      ACCEPT_EULA: "Y"
      UserID: "sa"
    ports:
      - "1433:1433"

  cloud_storage:
    build: cloudStorage/
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - DatabaseSettings:MsServer:Server=ms-sql-server
      - DatabaseSettings:MsServer:Port=1433
      - DatabaseSettings:MsServer:Database=cloudStorage
      - DatabaseSettings:MsServer:User=sa
      - DatabaseSettings:MsServer:Password=r00tR00t
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
